"""
VectaDB data models for AG2 (AutoGen) audit events.

Maps AG2 agent lifecycle events to VectaDB's event ingestion schema,
aligned with the W3C PROV provenance standard used throughout VectaDB.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field, model_validator


# ---------------------------------------------------------------------------
# Event type taxonomy
# ---------------------------------------------------------------------------

class AG2EventType(str, Enum):
    """Typed event taxonomy aligned with VectaDB's ontology for AG2 runs."""

    # Agent messaging
    AGENT_MESSAGE = "agent_message"       # Inbound message observed by an agent
    AGENT_REPLY = "agent_reply"           # Reply generated by an agent

    # Tool / function execution
    TOOL_CALL = "tool_call"               # Tool invocation start
    TOOL_RESULT = "tool_result"           # Tool invocation success
    TOOL_ERROR = "tool_error"             # Tool invocation failure

    # Retrieval (RAG)
    RETRIEVE_START = "retrieve_start"     # VectaDB hybrid query started
    RETRIEVE_END = "retrieve_end"         # VectaDB hybrid query completed

    # Group chat coordination
    GROUP_CHAT_START = "group_chat_start"
    GROUP_CHAT_END = "group_chat_end"
    GROUP_CHAT_SELECT = "group_chat_select"  # Speaker selection event


# ---------------------------------------------------------------------------
# Pydantic models matching VectaDB's EventIngestionRequest schema
# ---------------------------------------------------------------------------

class VectaDBSource(BaseModel):
    """Source metadata — identifies where this event originated."""
    system: str = "ag2"
    log_group: str = "ag2"
    log_stream: str = "default"
    log_id: str = ""


class VectaDBEvent(BaseModel):
    """
    Single event for VectaDB's /api/v1/events endpoint.

    Each event maps to a typed entity in the VectaDB ontology graph and
    optionally carries a vector embedding for semantic similarity search.
    """
    trace_id: Optional[str] = None
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    event_type: Optional[str] = None
    agent_id: Optional[str] = None
    session_id: Optional[str] = None
    properties: dict[str, Any] = Field(default_factory=dict)
    source: Optional[VectaDBSource] = None

    model_config = {"populate_by_name": True}

    def to_api_dict(self) -> dict[str, Any]:
        """Serialize to the exact shape VectaDB's REST API expects."""
        data: dict[str, Any] = {
            "timestamp": self.timestamp.isoformat(),
            "properties": self.properties,
        }
        if self.trace_id is not None:
            data["trace_id"] = self.trace_id
        if self.event_type is not None:
            data["event_type"] = self.event_type
        if self.agent_id is not None:
            data["agent_id"] = self.agent_id
        if self.session_id is not None:
            data["session_id"] = self.session_id
        if self.source is not None:
            data["source"] = self.source.model_dump()
        return data


class BulkIngestionOptions(BaseModel):
    auto_create_traces: bool = True
    generate_embeddings: bool = True
    extract_relationships: bool = False


class BulkIngestionRequest(BaseModel):
    events: list[VectaDBEvent]
    options: BulkIngestionOptions = Field(default_factory=BulkIngestionOptions)

    def to_api_dict(self) -> dict[str, Any]:
        return {
            "events": [e.to_api_dict() for e in self.events],
            "options": self.options.model_dump(),
        }


# ---------------------------------------------------------------------------
# Response models
# ---------------------------------------------------------------------------

class EventIngestionResponse(BaseModel):
    event_id: str
    trace_id: str
    created_at: datetime


class BulkIngestionError(BaseModel):
    index: int
    error: str


class BulkIngestionResponse(BaseModel):
    ingested: int
    failed: int
    trace_ids: list[str] = Field(default_factory=list)
    errors: list[BulkIngestionError] = Field(default_factory=list)


class HealthResponse(BaseModel):
    status: str
    version: str
    ontology_loaded: bool
    ontology_namespace: Optional[str] = None
    ontology_version: Optional[str] = None
